name: AIS Workflow 2

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unit tests
        run: mvn test -Dtest=es/codeurjc/ais/nitflex/unitary/*
      - name: Integration tests
        run: mvn test -Dtest=es/codeurjc/ais/nitflex/integration/*
      - name: System tests
        run: mvn test -Dtest=es/codeurjc/ais/nitflex/e2e/selenium/* -Dbrowser='firefox'
        