name: AIS Workflow 3

on:
  workflow_dispatch:
  #push:
   # branches:
    #- main

permissions:
  id-token: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Generate Docker image
          run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ github.sha }}
        - name: Login to DockerHub
          run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
        - name: Push image to DockerHub
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ github.sha }}

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Deploy container to Azure
          run: |
            az container create \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name nitflex \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/nitflex:${{ github.sha }} \
            --dns-name-label ariane-nicolas-nitflex \
            --ports 8080

    test:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Smoke Test
          run: mvn test -Dhost=http://ariane-nicolas-nitflex.westeurope.azurecontainer.io:8080/ -Dtest=es/codeurjc/ais/nitflex/smoke/*

